# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.25)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Mango::Mango Mango::MangoWidgets)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target Mango::Mango
add_library(Mango::Mango SHARED IMPORTED)

set_target_properties(Mango::Mango PROPERTIES
  INTERFACE_LINK_LIBRARIES "Mango::MangoWidgets"
)

# Create imported target Mango::MangoWidgets
add_library(Mango::MangoWidgets OBJECT IMPORTED)

set_target_properties(Mango::MangoWidgets PROPERTIES
  INTERFACE_LINK_LIBRARIES "android;EGL;log"
)

# Import target "Mango::Mango" for configuration "Debug"
set_property(TARGET Mango::Mango APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Mango::Mango PROPERTIES
  IMPORTED_LOCATION_DEBUG "${USER_HOME_DIR}/Desktop/MangoWidget/cmake-build-android/android/libs/arm64-v8a/libMango.so"
  IMPORTED_SONAME_DEBUG "libMango.so"
  )

# Import target "Mango::MangoWidgets" for configuration "Debug"
set_property(TARGET Mango::MangoWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Mango::MangoWidgets PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_OBJECTS_DEBUG "${USER_HOME_DIR}/Desktop/MangoWidget/cmake-build-android/plugins/platforms/android/CMakeFiles/MangoWidgets.dir/./JniObject.cpp.o;/Users/parhamoyan/Desktop/MangoWidget/cmake-build-android/plugins/platforms/android/CMakeFiles/MangoWidgets.dir/./Widget.cpp.o;/Users/parhamoyan/Desktop/MangoWidget/cmake-build-android/plugins/platforms/android/CMakeFiles/MangoWidgets.dir/./my-lib.cpp.o"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
